version: '3.2'

services:
  pg:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg-data:/var/lib/postgresql/data

  node-lab-backend:
    image: janobono/node-lab-backend:latest
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://app:app@pg:5432/app?schema=public
      - TOKEN_ISSUER=node-lab
      - TOKEN_SECRET=559b5bf9a85957c48b447f666922588fe12d26452189d52dec924b68f7713fdb5a85c681145ddeb4291e37ccd6224e87643cedd118eb425d546c560f35ef1f11
    depends_on:
      - pg
    labels:
      - traefik.enable=true
      - traefik.http.routers.node-lab-backend.rule=PathPrefix(`/api/node-lab-backend`)
      - traefik.http.routers.node-lab-backend.entrypoints=web
      - traefik.http.services.node-lab-backend.loadbalancer.server.port=8080

  node-lab-frontend:
    image: janobono/node-lab-frontend:latest
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.node-lab-frontend.rule=PathPrefix(`/`)
      - traefik.http.routers.node-lab-frontend.entrypoints=web
      - traefik.http.services.node-lab-frontend.loadbalancer.server.port=80

  node-lab-all-in-one:
    image: janobono/node-lab-all-in-one:latest
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://app:app@pg:5432/app?schema=public
    labels:
      - traefik.enable=true
      - traefik.http.routers.node-lab-all-in-one.rule=PathPrefix(`/all-in-one`)
      - traefik.http.routers.node-lab-all-in-one.entrypoints=web
      - traefik.http.services.node-lab-all-in-one.loadbalancer.server.port=80

  traefik:
    image: traefik:v2.3
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--log.level=DEBUG"
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  pg-data:
